#-------------------------------------------------------------------------------
# Description:
#   The purpose of this action definition, is to <INSERT_PURPOSE>
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# Action goal fields
#-------------------------------------------------------------------------------

# Box of the allocated space
SolidPrimitiveStamped allocated_space

# Drill specifications
CobotDrillingHoleArray holes_specification

---

#-------------------------------------------------------------------------------
# Action result fields
#-------------------------------------------------------------------------------

# Status of the sub-actions and the totals
CobotDrillingHoleState[] hole_states    # Status of the sub-actions 
uint32 n_correct                        # Number of correct sub-actions
uint32 n_incorrect                      # Number of incorrect sub-actions
uint32 n_cancelled                      # Number of cancelled sub-actions
uint32 n_skipped                        # Number of skipped sub-actions (can be re-tried later)

# Result of the drill request
float32[] measured_stack                # feed * time that drill torque was above threshold

# Result of the permanent fastening request
float32[] install_current		        # Motor current during fastener installation
float32[] install_time		            # Time needed to pull each fastener
float32[] pull_travel		            # Travel of pulling device when fastener stem breaks
float32 available_sealant		        # Amount of sealant available in ml

# Action success/failure indicator.
# Refer to penelope_aerospace_pl_msgs/msg/ResultCodes for defined error codes. 
uint16 result_code

# Status message (empty if action succeeded)
string message

---

#-------------------------------------------------------------------------------
# Action feedback fields
#-------------------------------------------------------------------------------

# Completion information
float32 percent_complete	# number between 0 - 100

# Box of the occupied_space
SolidPrimitiveStamped occupied_space 

# Status of the sub-actions and the totals
CobotDrillingHoleState[] hole_states    # Status of the sub-actions 
uint32 n_correct                        # Number of correct sub-actions
uint32 n_incorrect                      # Number of incorrect sub-actions
uint32 n_cancelled                      # Number of cancelled sub-actions
uint32 n_skipped                        # Number of skipped sub-actions (can be re-tried later)

# Result of the drill request
float32[] measured_stack                # feed * time that drill torque was above threshold

# Result of the permanent fastening request
float32[] install_current		        # Motor current during fastener installation
float32[] install_time		            # Time needed to pull each fastener
float32[] pull_travel		            # Travel of pulling device when fastener stem breaks
float32 available_sealant		        # Amount of sealant available in ml

# Generic module state
ModuleState module_state
