#-------------------------------------------------------------------------------
# Description:
#   The purpose of this action definition, is to control the DVM inspection 
#   module controlling the process of TNO.
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# Action goal fields
#-------------------------------------------------------------------------------

# Define 3D geometry location
SolidPrimitiveStamped allocated_space

# Define the location of the geometry file
string geometry_file_location # e.g. a '.ply' file

# TODO: Add description
string[] dvm_aquisition_parameters_directories
string[] dvm_aquisition_parameters_files

# Define process parameters
#   The robot settings
string[] robot_parameters # e.g. 'robot.ini'
#   The DVM acquisition settings including measurement data location 
string[] dvm_aquisition_parameters # e.g. 'DVM_acquisition.ini'
#   The DVM processing settings
string[] dvm_processing_parameters # e.g. 'DVM_processing.ini'
#   The material properties, thickness and dispersion curve of the panel 
string[] dvm_inspection_parameters # e.g. 'DVM_medium_parameters.ini'
#   File location of the results
string[] dvm_results_location # e.g. 'DVM_result_location.ini'

---

#-------------------------------------------------------------------------------
# Action result fields
#-------------------------------------------------------------------------------
DvmState[] measurement_state
bool[] measurement_ready
bool[] processed_data_available
bool[] ndt_approved
sensor_msgs/Image[] intensity_map
sensor_msgs/Image[] processed_scan

# Action success/failure indicator.
# Refer to penelope_aerospace_pl_msgs/msg/ResultCodes for defined error codes.
uint16 result_code

# Status message (empty if action succeeded)
string message

---

#-------------------------------------------------------------------------------
# Action feedback fields
#-------------------------------------------------------------------------------

# Completion information
float32[] percent_complete
float32[] time_to_completion # seconds

# Module specific state
# Refer to penelope_aerospace_pl_msgs/msg/DvmState for the definition
DvmState[] measurement_state

# Triggers state
TriggersState triggers_state

# Requested speed for the current movement
float32 movement_speed # m/s

# Increment of the triggers for the current scan
float32 increment_between_triggers # mm

# Processing and approval state information
bool[] processed_data_available
bool[] ndt_approved

# Generic module state
ModuleState module_state
