#-------------------------------------------------------------------------------
# Description:
#   The purpose of this action definition, is to control the DVM inspection 
#   module controlling the process of TNO.
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# Action goal fields
#-------------------------------------------------------------------------------

# Define 3D geometry location
SolidPrimitiveStamped allocated_space

# Define the location of the geometry file
string geometry_file_location # e.g. a '.ply' file

# Define process parameters
#   The robot settings
string[] robot_parameters # e.g. 'robot.ini'
#   The DVM acquisition settings including measurement data location 
string[] dvm_aquisition_parameters # e.g. 'DVM_acquisition.ini'
#   The DVM processing settings
string[] dvm_processing_parameters # e.g. 'DVM_processing.ini'
#   The material properties, thickness and dispersion curve of the panel 
string[] dvm_inspection_parameters # e.g. 'DVM_medium_parameters.ini'
#   File location of the results
string[] dvm_results_location # e.g. 'DVM_result_location.ini'

#   RoboDK simulation menu selection value 
int16 value
---

#-------------------------------------------------------------------------------
# Action result fields
#-------------------------------------------------------------------------------
DvmState[] measurement_state
bool[] measurement_ready
bool[] processed_data_available
bool[] ndt_approved

# Action success/failure indicator.
# Refer to penelope_aerospace_pl_msgs/msg/ResultCodes for defined error codes. 
uint16 result_code

# Status message (empty if action succeeded)
string message

# RoboDK simulation results
int16 result_value
float32 total_joint_distance
---

#-------------------------------------------------------------------------------
# Action feedback fields
#-------------------------------------------------------------------------------

# Completion information
float32[] percent_complete
float32[] time_to_completion

# Module specific state
# Refer to penelope_aerospace_pl_msgs/msg/DvmState for the definition
DvmState[] measurement_state

# Processing and approval state information
bool[] processed_data_available
bool[] ndt_approved

# Generic module state
ModuleState module_state

# RoboDK simulation results
int16 feedback_value
float64 feedback_pose_gantry
float32 feedback_pose_gantry_x
float32 feedback_pose_gantry_y
float32 feedback_pose_gantry_z
float32 feedback_joints_gantry_i
float32 feedback_joints_gantry_j
float32 feedback_joints_gantry_k
float32 feedback_welding_beam_l