#-------------------------------------------------------------------------------
# Infrared Thermography State (NLR)
#-------------------------------------------------------------------------------


#-------------------------------------------------------------------------------
# Description:
#   The purpose of this action definition, is to perform the infrared
#   thermography measurement (performed by NLR).
#   IR driving software is set up to execute the same exact measurment 4 times. 
#   Can halt if scenario of vibration exceeding 2mm appears. Measurement is
#   repeatable. Each measurement should last no longer than 10 minutes. If a
#   measurement must be broken off/halted, nothing is lost. The measurement can 
#   simply be restarted, after a pre-defined cooling down period
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# Action goal fields
#-------------------------------------------------------------------------------
geometry_msgs/PoseArray measurement_poses 	# Camera poses to take measurements at, alternatively trajectories can be send. 
string config_file 		# Location of a config file to load via the digital thread

---

#-------------------------------------------------------------------------------
# Action result fields
#-------------------------------------------------------------------------------
sensor_msgs/Image[] images # Processed images
uint16[] measurement_status # Succesful/Error type

# Action success/failure indicator.
# Refer to penelope_aerospace_pl_msgs/msg/ResultCodes for defined error codes. 
uint16 result_code

# Status message (empty if action succeeded)
string message

---

#-------------------------------------------------------------------------------
# Action feedback fields
#-------------------------------------------------------------------------------
# Indicator for the status of each measurement
uint16[] measurement_status 

# Module specific state
# Refer to penelope_aerospace_pl_msgs/msg/InfraredThermographyState for the
# definition of this module state
InfraredThermographyState process_state

# Generic module state
ModuleState module_state
