#-------------------------------------------------------------------------------
#   Definition of a Docking Position for an End Effector (GKN Fokker)
#
#   All locations in global axis system
#   All dimensions in mm
#-------------------------------------------------------------------------------

string uid                  # uid of the Docking Position

geometry_msgs/Pose pos      # location of the Docking Position
