#-------------------------------------------------------------------------------

# Description of the Assembly Action states:
#   ACTION_TYPE_MOVE_WAYPOINT
#       ...
#   ACTION_TYPE_INSTALL_PERMF  
#       ...
#   ACTION_TYPE_INSTALL_TEMPF
#       ...
#   ACTION_TYPE_REMOVE_TEMPF
#       ...

uint8 ACTION_TYPE_MOVE_WAYPOINT = 1
uint8 ACTION_TYPE_INSTALL_PERMF = 2
uint8 ACTION_TYPE_INSTALL_TEMPF = 3
uint8 ACTION_TYPE_REMOVE_TEMPF = 4

uint8 data