#-------------------------------------------------------------------------------
#   Assembly Hole Location Container (GKN Fokker)
#   Can be a product or a storage location. 
#   All locations in global axis system
#-------------------------------------------------------------------------------

string uid                              # uid of the container

AssemblyHoleLocation[] locations        # List of hole locations