#-------------------------------------------------------------------------------
#   Definition of an Assembly Waypoint (GKN Fokker)
#   
#   Waypoints can be used to manage the cobot movements
#
#   All locations in global axis system
#   All dimensions in mm
#-------------------------------------------------------------------------------

string uid                  # uid of the hole Waypoint

geometry_msgs/Pose pos      # location of the waypoint
