#-------------------------------------------------------------------------------
#   Definition of a temporary fastener (GKN Fokker)
#
#   All locations in global axis system
#   All dimensions in mm
#-------------------------------------------------------------------------------

string uid                              # uid of the drill

string loc_uid                          # uid of the location of the drill

float32 diam                            # diameter of the drill

float32 max_stack                       # the maximum stack in mm that can be drilled
